### ISSUE TITLE
Async iterator?

### ISSUE THREAD

**Issue by otakustay** [leebyron/iterall#13]
Since [Async Iterator](https://github.com/tc39/proposal-async-iteration) now is a stage-3 proposal and will land in engines soone, is there any plan for iterall to support it?

Further more, is it possible to support a sync-async-mixed iterator, which means the `next()` can return either Promise or other value in each iteration

**Comment by leebyron** [comment]
> Since Async Iterator now is a stage-3 proposal and will land in engines soone, is there any plan for iterall to support it?

💥 PR attached

> Further more, is it possible to support a sync-async-mixed iterator, which means the next() can return either Promise or other value in each iteration

Yes. This works similar to how `getIterator(obj)` will not return an iterator for an `obj` which does not define one, but `createIterator(obj)` will - assuming `obj` is array-like. `getAsyncIterator(obj)` will not return an async iterator for an `obj` which does not define one, but `createAsyncIterator(obj)` will if `obj` is array-like or can produce a normal sync iterator. Iterations which yields promises will be waited on before the wrapping async iterator will yield its value. This behavior is all well defined in https://tc39.github.io/proposal-async-iteration/#sec-async-from-sync-iterator-objects
