### ISSUE TITLE
Break out of `forAwaitEach`

### ISSUE THREAD

**Issue by noahsilas** [leebyron/iterall#21]
Part of the utility of async iterables is that you can break out of iteration, and avoid additional async work.

Consider a contrived example where we process an async iterator that fetches widgets from an API, providing a nice abstraction over paginated results:
```js
async function importWidgets(n = 10) {
  let count = 0;
  for await (let widget of getWidgets()) {
    if (import(widget)) {
      count++;
      if (count > n) { break; }
    }
  }
}
```

There's not an obvious way to replicate this with `forAwaitEach`, because we don't have the `break` language feature. My first thought is to check the return value of each iteration against some kind of sentinel. Our example might then look like:
```js
const iterall = require('iterall');

function importWidgets(n = 10) {
  let count = 0;
  return iterall.forAwaitEach(getWidgets(), (widget) => {
    if import(widget) {
      count++;
      if (count > n) { return iterall.break; }
  });
}
```

Would you be interested in receiving a PR to add a sentinel like this? Are there other strategies you would prefer to use to address this kind of loop escape? (Am I foolishly missing some easy way to achieve this that is already in the library?)

**Comment by leebyron** [comment]
You're right that this is a current limitation. It's intended to mirror the forEach function's behavior which also shares this limitation. I think having a sentinel return value for break makes sense - or as lodash [just returns the value `false`](https://lodash.com/docs/4.17.4#forEach).

I think it's important that this work for both functions in this library, but also careful for performance sensitivities. It would be great if you wrote a PR to include some micro-benchmark results.
