### ISSUE TITLE
Getting a build error with the latest version

### ISSUE THREAD

**Issue by ayafor** [leebyron/iterall#26]
Hi,

I have a build script that's pulling in the latest 1.1.2 version as a dependency on graphql 0.9.6, with the following error. It works fine on 1.1.1

├─┬ graphql@0.9.6 
│ └── iterall@1.1.2 

static/js/main.e1f5732b.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/iterall/index.js:644,0]

**Comment by jbarnette** [comment]
I'm seeing a similar problem trying to build a React app:

```
Failed to minify the code from this file: 

 	./node_modules/iterall/index.js:644 
```

And I see the same thing if I run `minify` directly:

```
$ git clone git@github.com:leebyron/iterall.git
$ cd iterall/
$ npm install minify
$ node_modules/.bin/minify index.js
Unexpected token: operator (>)
```

Seems like the minifier doesn't understand `=>`, added very recently in https://github.com/leebyron/iterall/pull/25.

**Comment by zeevgg** [comment]
please publish as soon possible..

**Comment by pleunv** [comment]
Can confirm, also running into this. As a temporary workaround (instead of downgrading `graphql-js`) you could also `yarn add iteral@1.1.1` and add the following the `package.json`:

```json
"resolutions": {
  "iterall": "1.1.1"
}
```

**Comment by joachimvdnab** [comment]
I am having the same problem. Thanks @pleunv for the temporary fix!

**Comment by brucewpaul** [comment]
same here!

**Comment by gerardobort** [comment]
:shipit: please!!!

**Comment by leebyron** [comment]
Thanks for the report, everyone. A new version with a fix for this issue was just released.
