### ISSUE TITLE
feature request add mapAsyncIterator

### ISSUE THREAD

**Issue by dh94** [leebyron/iterall#47]
add mapAsyncIterator functionality
example implementation:
https://github.com/graphql/graphql-js/blob/master/src/subscription/mapAsyncIterator.js

**Comment by dh94** [comment]
relates to
https://github.com/graphql/graphql-js/issues/1354

**Comment by dh94** [comment]
@leebyron what do you think?

**Comment by leebyron** [comment]
This isn't the right place for this utility function.

See https://github.com/leebyron/iterall/blob/master/README.md#faq - "where are map, filter, reduce?"

GraphQL.js uses that function to keep byte weight and dependencies minimal, however if you're looking for a toolbelt of higher level functions for async iterators, I'd recommend taking a look at https://github.com/ReactiveX/IxJS
