### ISSUE TITLE
createAsyncIterator missing return() & throw()

### ISSUE THREAD

**Issue by thomassuckow** [leebyron/iterall#48]
In my interpretation of
https://tc39.github.io/proposal-async-iteration/#sec-async-from-sync-iterator-objects
I believe the return() and throw() methods are required to be an async iterator / "AsyncGenerator".

Thus, createAsyncIterator when creating an iterator for a native type such as Array should include the return() and throw() methods to cause the iteration to cease. Thus would allow it to behave as if it was a real AsyncIterator.

Tested on Chrome 68, for what it is worth.

**Comment by grantwwu** [comment]
+1 on this, this is pretty important imo.  Is this repo still being looked at?  I could probably contribute a patch...

**Comment by grantwwu** [comment]
Woah, thanks for getting to this.  I hope this helps other people!
